site_name: ZodiPy
site_description: Zodiacal emission simulations with python
repo_url: https://github.com/cosmoglobe/zodipy

theme:
  name: "material"
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      toggle:
        icon: material/lightbulb
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      toggle:
        icon:  material/lightbulb-outline
        name: Switch to light mode
  icon:
    logo: material/book-open-page-variant
  features:
    - search.suggest
    - search.highlight
    - content.tabs.link
    - navigation.indexes
    - content.tooltips
    - navigation.path
    - content.code.annotate
    - content.code.copy
    - content.code.select
    - navigation.tabs
markdown_extensions:
  - markdown_include.include:
      base_path: docs
  - admonition
  - pymdownx.details
  - pymdownx.highlight
  - pymdownx.superfences
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.tabbed:
      alternate_style: true
extra_javascript:
  - javascripts/mathjax.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js

nav:
  - Overview: index.md
  - introduction.md
  - install.md
  - usage.md
  - reference.md

plugins:
- search
- mkdocstrings:
    handlers:
      python:
        options:
          inherited_members: true
          merge_init_into_class: true
          members_order: source
          separate_signature: true
          unwrap_annotated: true
          docstring_section_style: spacy
          signature_crossrefs: true
          show_symbol_type_heading: true
          show_symbol_type_toc: true
# - mkdocstrings:
#     default_handler: python
#     handlers:
#       options:
#         merge_init_into_class: true