name: mkdocs-deploy
run-name: ${{ github.actor }} is deploying the documentation to gh-pages.
on:
  push:
    branches:
      - main
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python 3.10
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install and configure Poetry
        uses: snok/install-poetry@v1.3.4
        with:
          version: 1.2.2
          virtualenvs-in-project: true

      - name: Install dependencies
        run: poetry install
        if: steps.cached-poetry-dependencies.outputs.cache-hit != 'true'
        
      - name: Deploy docs to gh-pages
        run: |
          source $VENV
          mkdocs gh-deploy --force --clean --verbose
