name: unit-and-property-tests
run-name: ${{ github.actor }} is running unit and property tests.
on:
  - push
  - pull_request
jobs:
  run-tests:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]
        python-versions: ['3.9', '3.10', '3.11', '3.12']
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install and configure Poetry
        uses: snok/install-poetry@v1.4.1
        with:
          version: 1.2.2
          virtualenvs-in-project: true

      - name: Install dependencies
        run: poetry install
        if: steps.cached-poetry-dependencies.outputs.cache-hit != 'true'

      - name: Typecheck with mypy
        run: |
          source $VENV
          mypy ./zodipy

      - name: Check linting with ruff
        run: |
          source $VENV
          ruff check

      - name: Check formating with ruff
        run: |
          source $VENV
          ruff format --check

      - name: Test with pytest
        run: |
          source $VENV
          pytest tests -v --cov=./zodipy --cov-report=xml:./coverage.xml --cov-report term-missing

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v5
        with:
          files: coverage.xml
          fail_ci_if_error: false