name: unit-and-property-tests
run-name: ${{ github.actor }} is running unit and property tests.
on:
  - push
  - pull_request
jobs:
  run-tests:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]
        python-versions: ['3.9', '3.10', '3.11', '3.12', '3.13']
    steps:
      - uses: actions/checkout@v7
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v7
        with:
          python-version: ${{ matrix.python-version }}

      - name: Set up uv
        uses: astral-sh/setup-uv@5
        with:
	  enable-cache: true

      - name: Install dependencies
        run: uv sync --locked --dev
        if: steps.cached-poetry-dependencies.outputs.cache-hit != 'true'

      - name: Typecheck with mypy
        run: |
          source $VENV
          mypy ./zodipy

      - name: Check linting with ruff
        run: |
          source $VENV
          uvx ruff check

      - name: Check formating with ruff
        run: |
          source $VENV
          uvx ruff format --check

      - name: Test with pytest
        run: |
          source $VENV
          uv run pytest tests -v --cov=./zodipy --cov-report=xml:./coverage.xml --cov-report term-missing

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v7
        with:
          files: coverage.xml
          fail_ci_if_error: false
